ecommerce/cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [
    path('add-cart/<int:p>', views.add_cart,name="add_cart"),
    path('cart_remove/<int:p>', views.cart_remove,name="cart_remove"),
    path('full_remove/<int:p>', views.full_remove,name="full_remove"),
    path('cartview',views.cartview,name="cartview"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search',include('search.urls')),
    path('cart/',include('cart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('', views.searchresult,name="searchresult"),


]

ecommerce/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('', views.allprodcat,name="allprodcat"),
    path('allproducts/<slug:e>',views.allproducts,name="allproducts"),
    path('viewproduct/<slug:e>',views.viewproduct,name="viewproduct"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout")

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateField(auto_now_add=True)
    active=models.BooleanField(default=True)

    def __str__(self):
        return self.products.name

    def subtotal(self):
        return self.quantity*self.products.price

class Account(models.Model):
    accntnumber=models.CharField(max_length=20)
    acctype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.accntnumber

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")
    noofitens=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.noofitens * self.products.price

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart,Account,Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


@login_required
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
        cart.save()

    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,products=product,quantity=1)
        cart.save()
    return redirect('cart:cartview')

@login_required
def cartview(request):
    total=0
    user=request.user
    try:
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity*i.products.price

    except Cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cart,'total':total})


@login_required
def cart_remove(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity>1:
            cart.quantity-=1
            cart.save()
        else:
            cart.delete()

    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')


def full_remove(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        cart.delete()

    except Cart.DoesNotExist:
        pass
    return redirect('cart:cartview')


@login_required
def orderform(request):
    total=0
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.products.price
        ac=Account.objects.get(accntnumber=n)
        if(ac.amount >= total):
            ac.amount=ac.amount-total
            ac.save()

            for i in cart:
                o=Order.objects.create(user=u,products=i.products,address=a,phone=p,order_status="Paid",noofitens=i.quantity)
                i.products.stock=i.products.stock-i.quantity
                i.save()
                o.save()
            cart.delete()
            msg="Ordered Successfully"
            return render(request,"orderdetail.html",{'msg':msg,'total':total})
        else:
            msg="Insufficient amount,You can't place an order"
            return render(request,'orderdetail.html',{'msg':msg})

    return render(request,'orderform.html')

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u,order_status="Paid")
    return render(request,'orderview.html',{'o':o,'name':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
def searchresult(request):
    query=""
    products=""
    if(request.method=="POST"):
        query=request.POST.get('q')
        #print(query)
        if(query):
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>
<body>
<div class="container-fluid">
    <header>
    <center><img src="{% static 'img/logo.png' %}" height="100px width=100px"  alt="img"></center>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">ECOMMERCE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto ">
      <li class="nav-item active">
        <a class="nav-link" aria-current="page" href="{% url 'shop:allprodcat' %}">Home</a>
      </li>



      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          All Categories
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
            {% endfor %}
        </ul>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item active">
        <a class="nav-link" aria-current="page" href="{% url 'cart:cartview' %}"><i style="font-size:20px;" class="fa fa-cart-shopping" style="color: #000000;"></i>{{item_count}}</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
      </li>

        <li class="nav-item active">
        <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
      </li>
        {% else %}
        <li class="nav-item active">
        <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
      </li>
        <li class="nav-item active">
        <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
      </li>
        {% endif %}
    </ul>
    <form method="POST" class="d-flex" action="{% url 'search:searchresult' %}">
        {% csrf_token %}
      <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    </header>
</div>
{% block content %}
{% endblock %}
<footer>
    <div style="background-color:light;text-align:center;font-weight:bold;color:black;height:60px;width:100%;bottom:0">
        <p><i><i class="fa-regular fa-copyright"></i></i>ECOMMERCE pvt ltd.All rights reserved</p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid" style="margin-bottom:100px">
    {% if not cart %}
    <div class="text-center" style="margin-bottom:100px">
        <h1 class="text-center">Cart is Empty</h1>
        <strong><a href="{% url 'shop:allprodcat' %}" class="btn btn-primary ">Continue Shopping</a> </strong>
    </div>

     {% else%}


<div class="row">
    <h1 class="text-center">Shopping cart</h1>
  <div class="col-md-6">
    <table class="table table-bordered">
     <tr>
      <th colspan="5" class="text-center"> cart items</th>
       {% for i in cart %}
     </tr>
     <tr>
      <td><img src="{{i.products.image.url}}" height="100px" width="100px"></td>
      <td><strong>{{i.products.name}}</strong></td>
      <td>
          <p><strong>ProductsId:</strong>{{i.products.id}}</p>
          <p><strong>Unit Price:</strong>{{i.products.price}}</p>
      <p><strong>Quantity:</strong>{{i.quantity}}*{{i.products.price}}</p>
      </td>
         <td><strong>Subtotal:</strong>{{i.subtotal}}</td>
         <td>
             {% if i.quantity < i.products.stock %}
             <a href="{% url 'cart:add_cart' i.products.id %}"><i class="fa-solid fa-circle-plus text-success"></i></a>
             <a href="{% url 'cart:cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus text-primary"></i></a>
             <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-solid fa-trash text-danger"></i></a>

             {% else %}
             <a href="{% url 'cart_remove' i.products.id %}"><i class="fa-solid fa-circle-minus text-primary"></i></a>
             <a href="{% url 'cart:full_remove' i.products.id %}"><i class="fa-solid fa-trash text-danger"></i></a>
             {% endif %}

         </td>
     </tr>
        {% endfor %}
    </table>
  </div>
    <div class="col-md-6" style="position:relative;">
        <table class="table table-bordered text-center">
            <tr><th colspan="5" class="text-center">Check Out</th></tr>
            <tr><td> <strong>TOTAL PRICE:</strong>{{total}}</td></tr>
    </table>
        <a href="{% url 'shop:allprodcat' %}" class="btn btn-success" style="width:200px;position:absolute;">Continue Shopping</a>
        <a href="{% url 'cart:orderform' %}" class="btn btn-secondary" style="position:absolute;right:10px;width:200px">Place Order</a>
    </div>

</div>
    {% endif %}
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div><img src="{% static 'img/banner.jpg' %}" height="500px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h1 class="text-center">OUR COLLECTIONS</h1>
    <p class="text-align:justify;">Discover an unparalleled online shopping experience at our cutting-edge ecommerce website. We bring you a vast and diverse collection of products, exceptional customer service, and a user-friendly interface that will make your shopping journey a breeze. Browse through our extensive product catalog, carefully curated to cater to your every need. From fashion and accessories to electronics, home decor, beauty products, and more, we have everything you're looking for, all in one convenient place. Our intuitive search and filtering system allows you to find exactly what you're looking for, with options to refine your search by category, brand, price range, and customer ratings. Say goodbye to endless scrolling and wasted time, and say hello to a seamless shopping experience.Discover personalized recommendations tailored to your unique tastes and preferences. Our intelligent recommendation engine analyzes your browsing and purchase history to suggest items you're likely to love. Get ready to be pleasantly surprised by new and exciting finds.</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="">
                <img src="{{i.image.url}}" height="250px" width="100%" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title text-center">{{i.name}}</h5>

                    <a href="{% url 'shop:allproducts' i.slug %}" class="btn btn-primary" style="position:relative;left:38%;">PRODUCTS</a>
                </div>
            </div>
        </div>
             {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 mt-5">
        <img src="{{p.image.url}}" height="400px" width="500px"></div>
        <div class="col-sm-6 mt-5">
        <h2>{{p.name}}</h2>
        <h3>Price:{{p.price}}</h3>
            <h3>Product Description</h3>
            <p style="text-align:justify">{{p.description}}</p>
            {% if p.stock <= 0 %}
            <h2>Out of Stock</h2>
            {% else %}
            <a href="{% url 'cart:add_cart' p.id %}" class="btn btn-primary">ADD TO CART</a>
        {% endif %}
        </div></div></div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<h1>LOGIN</h1>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter Username">
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter Password">
    </div>
     <div class="mb-3">
        <input type="submit">
    </div>
</form>
    </div>

{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
  <h2 class="text-center text-success">{{msg}}</h2>
  <h5 class="text-center text-danger">Thank You......</h5>
  <p class="text-center"><a href="{% url 'shop:allprodcat' %}">Continue Shopping</a> </p>
</div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="cotainer">
    <form method="POST">
        {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Address</label>
        <input type="text" class="form-control" name="a" placeholder="Enter the address">
    </div>
        <div class="mb-3">
            <label class="form-label">Phone</label>
            <input type="text" class="form-control" name="p" placeholder="Enter the phone number">
        </div>
         <div class="mb-3">
            <label class="form-label">Account number</label>
            <input type="text" class="form-control" name="n" placeholder="Enter the account number">
        </div>
         <div class="mb-3">

            <input type="submit" class="btn btn-primary">
        </div>
        </form>

</div>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h5 class="text-center">Name of the Customer:{{name}}</h5>
        {% for i in o %}
        <div class="col-sm-5 py-3" style="border:2px solid gray">
          <center><img src="{{i.products.image.url}}" height="200px" width="200px"></center>
        </div>
        <div class="col-sm-7 py-3 text-center" style="border:2px solid gray">
            Delivery Address :{{i.address}}<br>
            Phone number :{{i.phone}}<br>
            {{i.products.name}}<br>
            {{i.products.price}}<br>
            Quantity Ordered:{{i.noofitems}}<br>
            Subtotal:{{i.subtotal}}<br>
            <strong class="text-primary">Ordered on {{i.date_added}}</strong><br>
            <strong class="text-success">Delivery status :{{i.delivery_status}}</strong>
    </div>
        {% endfor %}
    </div></div>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
<img src="{{c.image.url}}" alt="img" height="400px" width="100%">
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <h2 class="text-center" style="color:red;font-weight:bold;">{{c.name}}</h2>
    <br>
    <p style="text-align:justify">{{c.description}}</p></div>

<div class="container-fluid">
    <div class="row">
        {%for i in p %}
        <div class=" col-md-4" style="height:450px">
            <div class="card" style="background:#b39ddb">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="color:green">
                 <h5 class="card-title text-center" style="text-transform:uppercase;">{{i.name}}</h5>
                    <h6 class="card-title text-center" style="text-transform:uppercase;">{{i.price}}</h6>
                <a href="{% url 'shop:viewproduct' i.slug %}" class="btn btn-outline-light" style="background:purple;position:relative;left:38%;">DETAILS</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}add{% endblock %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
<h1>SIGN UP</h1>
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter Username">
    </div>
    <div class="mb-3">
        <label class="form-label">First name</label>
        <input type="text" class="form-control" name="f" placeholder="Enter First name">
    </div>
    <div class="mb-3">
        <label class="form-label">Last name</label>
        <input type="text" class="form-control" name="l" placeholder="Enter Last name">
    </div>
    <div class="mb-3">
        <label class="form-label">Email</label>
        <input type="email" class="form-control" name="e" placeholder="Enter Email">
    </div>
    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter Password">
    </div>
    <div class="mb-3">
        <label class="form-label">Confirm Password</label>
        <input type="password" class="form-control" name="cp" placeholder="Enter Password">
    </div>
    <div class="mb-3">
        <input type="submit" class="form-control">
    </div>
</form>
    </div>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h3 class="text-center">You have searched for {{query}}</h3>
</div>
<div class="container" style="margin-bottom:100px;">
    <h6 class="text-center">SEARCH RESULTS</h6>
    <div class="row">
        {%for i in products %}
        <div class=" col-md-4" style="height:450px">
            <div class="card" style="background:#b39ddb">
                <img src="{{i.image.url}}" class="card-img-top"  alt="..." height="250px">
                <div class="card-body" style="color:green">
                 <h5 class="card-title text-center" style="text-transform:uppercase;">{{i.name}}</h5>
                <a href="{% url 'shop:viewproduct' i.slug %}" class="btn btn-outline-light" style="background:purple;position:relative;left:38%;">DETAILS</a>
                </div>
            </div>
        </div>
        {% empty %}
        <h5 class="text-center text-danger">0 Results Found</h5>
        {% endfor %}
</div>
{% endblock %}